site_name: Siddhi IO File
site_description: Siddhi IO File Extension
site_author: WSO2
site_url: https://siddhi-io.github.io/siddhi-io-file/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-IO-file
repo_url: https://github.com/siddhi-io/siddhi-io-file
copyright: Copyright &copy; 2011 - 2020 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc:
    permalink: true
- codehilite:
    guess_lang: false
- pymdownx.tasklist:
    custom_checkbox: true
- markdown.extensions.attr_list: null
pages:
- Welcome: index.md
- API Docs:
  - latest: api/latest.md
  - 2.0.8: api/2.0.8.md
  - 2.0.7: api/2.0.7.md
  - 2.0.6: api/2.0.6.md
  - 2.0.5: api/2.0.5.md
  - 2.0.4: api/2.0.4.md
  - 2.0.3: api/2.0.3.md
  - 2.0.2: api/2.0.2.md
  - 2.0.1: api/2.0.1.md
  - 2.0.0: api/2.0.0.md
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.14: api/1.0.14.md
  - 1.0.13: api/1.0.13.md
  - 1.0.12: api/1.0.12.md
  - 1.0.11: api/1.0.11.md
  - 1.0.10: api/1.0.10.md
  - 1.0.9: api/1.0.9.md
  - 1.0.8: api/1.0.8.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0-M12: api/1.0.0-M12.md
  - 1.0.0-M11: api/1.0.0-M11.md
  - 1.0.0-M10: api/1.0.0-M10.md
  - 1.0.0: api/1.0.0.md
- License: about/license.md
